name: CI/CD Pipeline

on:
  push:
    paths:
      - 'challenge-3/index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-3
          file: ./challenge-3/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with Docker Compose
        working-directory: ./challenge-3
        run: |
          docker-compose down
          docker-compose up -d